wireplumber.profiles = {
  main = {
    node.software-dsp = required
  }
}

node.software-dsp.rules = [
  {
    matches = [
      { "node.name" = "alsa_output.usb-Synaptics_CX31993_MAX97220-00.analog-stereo" }
    ]
    actions = {
      create-filter = {
        filter-path = "/home/pedrog/.config/wireplumber/wireplumber.conf.d/filters/zero-red.conf"
      }
    }
  }
]
