-- Plugin settings --
require('config.gruvbox')
require('config.treesitter')
require('config.cmp')
require('config.mason')
require('config.lualine')
require('config.ibl')
require('config.tree')
require('config.comment')
require('config.colorizer')
require('config.alpha')
require('config.telescope')
require('config.lspconfig')
require('config.surround')
require('config.autopairs')
require('config.trouble')
require('config.luasnip')
