theme = "gruvbox"

[editor]
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "version-control", "spinner", "diagnostics", "file-base-name"]
center = []
right = ["file-encoding", "file-line-ending", "file-type", "position-percentage", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false